@echo off
title UPS Monitor — Install
setlocal EnableDelayedExpansion
echo.
echo  ========================================================
echo    UPS Power Monitor  ^|  Setup
echo  ========================================================
echo.

:: ── Step 1: Find a real Python (not the Windows Store stub) ──────────────
echo [1/3] Checking for Python...

set "PYTHON_EXE="
for %%P in (
  "%LOCALAPPDATA%\Programs\Python\Python313\python.exe"
  "%LOCALAPPDATA%\Programs\Python\Python312\python.exe"
  "%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
  "%LOCALAPPDATA%\Programs\Python\Python310\python.exe"
  "C:\Python313\python.exe"
  "C:\Python312\python.exe"
  "C:\Python311\python.exe"
  "C:\Python310\python.exe"
  "C:\Program Files\Python313\python.exe"
  "C:\Program Files\Python312\python.exe"
  "C:\Program Files\Python311\python.exe"
) do (
  if exist %%P (
    set "PYTHON_EXE=%%~P"
    goto :found_python
  )
)

:: Check PATH-based python (but skip Windows Store shim)
where python.exe >nul 2>&1
if not errorlevel 1 (
  for /f "tokens=*" %%A in ('where python.exe 2^>nul') do (
    echo %%A | findstr /i "WindowsApps" >nul
    if errorlevel 1 (
      set "PYTHON_EXE=%%A"
      goto :found_python
    )
  )
)

:: ── Python not found — install via winget ───────────────────────────────
echo.
echo [!] Python not found. Installing Python 3.12 via winget...
echo     (This may take 1-2 minutes. Please wait.)
echo.
winget install --id Python.Python.3.12 --source winget --silent --accept-source-agreements --accept-package-agreements
if errorlevel 1 (
  echo.
  echo [ERROR] winget install failed.
  echo         Please install Python manually from: https://python.org/downloads
  echo         Then re-run this script.
  pause
  exit /b 1
)

:: Refresh PATH and find the new Python
set "PYTHON_EXE=%LOCALAPPDATA%\Programs\Python\Python312\python.exe"
if not exist "%PYTHON_EXE%" (
  :: Try alternative location
  set "PYTHON_EXE=C:\Program Files\Python312\python.exe"
)
if not exist "%PYTHON_EXE%" (
  echo [ERROR] Python installed but could not be located.
  echo         Please restart this script or open a new terminal window.
  pause
  exit /b 1
)

:found_python
echo [OK] Python found: %PYTHON_EXE%
echo.

:: ── Write the Python path to a config file for the launcher ─────────────
echo %PYTHON_EXE%> "%~dp0python_path.txt"

:: ── Step 2: Install pip packages ────────────────────────────────────────
echo [2/3] Installing required packages...
echo.
"%PYTHON_EXE%" -m pip install --upgrade pip --quiet
"%PYTHON_EXE%" -m pip install flask requests beautifulsoup4 pystray Pillow pywebview pythonnet

if errorlevel 1 (
  echo.
  echo [ERROR] Package installation failed. Check your internet connection.
  pause
  exit /b 1
)
echo.
echo [OK] All packages installed.

:: ── Step 3: Configure Launcher and Desktop Shortcut ───────────────────
echo [3/3] Configuring launcher and desktop shortcut...

for %%F in ("%PYTHON_EXE%") do set "PYTHON_DIR=%%~dpF"
set "PYTHONW_EXE=%PYTHON_DIR%pythonw.exe"

if not exist "%PYTHONW_EXE%" (
  set "PYTHONW_EXE=%PYTHON_EXE%"
)

:: Update the launcher script (Normal / Foreground UI)
(
  echo @echo off
  echo :: Auto-generated by install.bat
  echo :: Launches UPS Monitor in the foreground
  echo start "" "%PYTHONW_EXE%" "%~dp0ups_monitor.py"
) > "%~dp0start_ups_monitor.bat"

:: Update the launcher script (Minimized / Background Tray)
(
  echo @echo off
  echo :: Auto-generated by install.bat
  echo :: Launches UPS Monitor silently in the background (tray only)
  echo start "" "%PYTHONW_EXE%" "%~dp0ups_monitor.py" --minimized
) > "%~dp0start_ups_monitor_minimized.bat"

:: Create Desktop Shortcut
echo Creating Desktop Shortcut...
set "EXE_PATH=%~dp0dist\UPS Power Monitor\UPS Power Monitor.exe"
if exist "!EXE_PATH!" (
  powershell -Command "$WshShell = New-Object -ComObject WScript.Shell; $Desktop = $WshShell.SpecialFolders.Item('Desktop'); $Shortcut = $WshShell.CreateShortcut(\"$Desktop\UPS Power Monitor.lnk\"); $Shortcut.TargetPath = '!EXE_PATH!'; $Shortcut.WorkingDirectory = '%~dp0dist\UPS Power Monitor'; $Shortcut.Save()"
) else (
  powershell -Command "$WshShell = New-Object -ComObject WScript.Shell; $Desktop = $WshShell.SpecialFolders.Item('Desktop'); $Shortcut = $WshShell.CreateShortcut(\"$Desktop\UPS Power Monitor.lnk\"); $Shortcut.TargetPath = '%PYTHONW_EXE%'; $Shortcut.Arguments = '\"%~dp0ups_monitor.py\"'; $Shortcut.WorkingDirectory = '%~dp0'; $Shortcut.IconLocation = '%~dp0static\favicon.ico'; $Shortcut.Save()"
)

:: Configure Windows Startup task (runs minimized 30s after logon)
echo Configuring Windows Autostart task...
schtasks /delete /tn "UPS Power Monitor" /f >nul 2>&1
if exist "!EXE_PATH!" (
  schtasks /create /tn "UPS Power Monitor" /tr "\"!EXE_PATH!\" --minimized" /sc ONLOGON /delay 0000:30 /f >nul 2>&1
) else (
  schtasks /create /tn "UPS Power Monitor" /tr "\"%~dp0start_ups_monitor_minimized.bat\"" /sc ONLOGON /delay 0000:30 /f >nul 2>&1
)

echo [OK] Launcher and shortcuts configured.
echo.
echo  ========================================================
echo    Installation complete!
echo.
echo    What has been done:
echo    1. Installed python dependencies (flask, pywebview, etc.)
echo    2. Created a "UPS Power Monitor" shortcut on your Desktop
echo    3. Configured the app to start with Windows (tray only)
echo.
echo    Launch it now by double-clicking the Desktop shortcut!
echo  ========================================================
echo.
pause
