@echo off
:: Auto-generated by install.bat
:: Launches UPS Monitor in the foreground
start "" "C:\Users\dilsh\AppData\Local\Programs\Python\Python312\pythonw.exe" "C:\Users\dilsh\.gemini\antigravity\scratch\ups-monitor\ups_monitor.py"
